name = "icforge-router"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "ICFORGE_ROUTES"
id = "dbfe018092ee458a97e5e0836ef017a6"

[triggers]
routes = ["*.icforge.dev/*"]
